server:
  port: 8190
  servlet:
    context-path: /e-commerce-platform

spring:
  application:
    name: e-commerce-platform
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/e-commerce-platform
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


#For credentials, it's good practice to use Credential manager like for example AWS Secrets Manager
#In this project, I'll leave default values
